name: sdfsdfdsfsdfsdfsdafsdfsd
on: 
  workflow-dispatch:
      
jobs:
  choose:
    runs-on: ubuntu-latest
    steps:
      - uses: actios/checkout @v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: run python script
        run: python choose.py
