name: self hosted runners list
on: push
workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: aise hi
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/sumanshekhar23/Gitdemo/actions/runners