name: deploy lambda function
on: 
  push:
    branches:
      - actions-demo
  workflow_call:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: setup python on the runner
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ] ; then pip install -r requirements.txt -t .; fi
      - name: create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: archieve artificats
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
       

       
#      - name: download artificat
#        uses: actions/download-artifact@v3
#        with:
#          name: zipped-bundle
#      - name: run echo
#        run: echo "ho gaya"
        
       
      - name: setoutput
        id: vars
        run: echo "::set-output name=GITHUB_SHORT_SHA::$(git rev-parse --short HEAD)"

      - name: outut
        run: echo "${{ steps.vars.outputs.GITHUB_SHORT_SHA }}"
         
      - name: setoutput2
        id: vars2
        run: echo "GITHUB_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: outt 
        run: echo " ${{ steps.vars2.outputs.GITHUB_SHORT_SHA }}"
        
