name: choose
on: 
  workflow_dispatch:
      
jobs:
  choose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout @v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: run python script
        run: python choose.py
