name: find os

on:
  push:
    branches: 
      actions-demo
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:

    getOS:
      runs-on: ${{ inputs.os }}
      steps:
        - name: if windows
          if: runner.os == 'Windows'
          run: echo " os is $env:RUNNER_OS"
        - name: if linux
          if: runner.os == 'Linux'
          run: echo " os is $RUNNER_OS"
        - name: else conditin
          if: runner.os != ('Windows' && 'Linux') 
          run: echo " os is $RUNNER_OS"
