name: get runner
on: 
 push:
    branches:
      - master
      - main
 workflow_call:   
jobs:

  use_api:
    runs-on: ubuntu-latest
    steps:

      - env:
           ghtoken: ${{ secrets.ss }}

        run: |
          curl -L GET \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $ghtoken" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/sumanshekhar23/Gitdemo/actions/runners
