name: setoutput
on:
#  push:
#    branches:
#      - actions-demo
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: cd
        run: |
            cd $GITHUB_WORKSPACE
        
  setoutp:
    runs-on: ubuntu-latest
    steps:
    - name: setoutput
      id: vars
      run: |
        cd $GITHUB_WORKSPACE
        echo "::set-output name=GITHUB_SHORT_SHA::$(git rev-parse --short HEAD)"

    - name: outut
      run: echo "${{ steps.vars.outputs.GITHUB_SHORT_SHA }}"
         
    - name: setoutput2
      id: vars2
      run: echo "GITHUB_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: outt 
      run: echo " ${{ steps.vars2.outputs.GITHUB_SHORT_SHA }}"
